In [3]:
import meshplot as mp
import numpy as np

import xml.etree.ElementTree as ET

def load_color_profile(file_path):
    tree = ET.parse(file_path)
    root = tree.getroot()
    vertices = [float(x) for x in root.find("Tags").find("gamutBoundaryDescType").find("Vertices").find("PCSValues").text.split()]
    vertices = np.reshape(vertices, (-1, 3))
    print(vertices)
    triangles = np.array([[int(x) for x in t.text.split()] for t in root.find("Tags").find("gamutBoundaryDescType").find("Triangles")])
    print(triangles)
    return vertices, triangles

def main():
    vertices, triangles = load_color_profile("profiles/sRGB_D65_MAT.xml")
    mp.plot(vertices, triangles, return_plot=True, shading={"flat": False, "wireframe": True})

if __name__ == "__main__":
    main()

[[0.9504 1.     1.0889]
 [0.9504 1.     1.0889]
 [0.9504 1.     1.0889]
 ...
 [0.     0.     0.    ]
 [0.     0.     0.    ]
 [0.     0.     0.    ]]
[[  1   2  19]
 [  2   3  20]
 [  3   4  21]
 ...
 [448 466 465]
 [449 467 466]
 [450 468 467]]


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.4751999…

In [ ]:
import 